Classic BPF Fuzzing Strategy - Random Instruction Generation
google/buzzer pull request #70
Opened 2024-07-24 15:05 UTC by Negroni1

2024-07-24 20:17 UTC, thatjiaozi requested changes

2024-07-24 20:17 UTC, thatjiaozi commented on main.go
> +	strategyName       = flag.String("strategy", "cbpf_random_instruction", "Strategy to use for fuzzing")
let's leave this as playground :)

2024-07-24 20:17 UTC, thatjiaozi commented on pkg/cbpf/instruction_generators.go
> +func RandomSize() pb.StLdSize {
if we are using the same functions in ebpf and cbpf, can we merge them in a common library?

2024-08-05 17:53 UTC, Negroni1 commented on main.go
> +	strategyName       = flag.String("strategy", "cbpf_random_instruction", "Strategy to use for fuzzing")
Done

2024-08-05 18:28 UTC, thatjiaozi approved these changes

2024-08-05 19:34 UTC, merged